# -----------------------------------------------------------------------------
#
# HELLO PYTHON EXAMPLE
#
# -----------------------------------------------------------------------------

# Example project demonstrating Python setup with SDK.
# Overrides default Python version to use 3.10.

# --
# ## SDK Integration

include ../../setup.mk

# --
# ## Python Configuration

PYTHON_VERSION=3.10 ## Python version for this project

# EOF
